### ISSUE TITLE
How to start app

### ISSUE THREAD

**Issue by bajki** [gustoase/vue-gui#1]
Hi, im getting { "ok": 0, "errmsg": "not authorized on admin to execute command { find: \"projects\", filter: {}, projection: {}, returnKey: false, showRecordId: false, $db: \"admin\" }", "code": 13, "codeName": "Unauthorized", "name": "MongoError" }
How, to fix this?

**Comment by gustoase** [comment]
Hi) mongo is running? And db " vue-gui" is created?

**Comment by gustoase** [comment]
I'll update the documentation now, sorry for not describing the moments
**UPD**
readme is updated

**Comment by gustoase** [comment]
@bajki 
I checked it myself, I can't run it.
I will correct tomorrow morning, and everything will work

**Comment by bajki** [comment]
Awesome!!

**Comment by gustoase** [comment]
@bajki temporarily remove sockets.io and mongo, just try to update the branch, and run npm run serve

**Comment by bajki** [comment]
One more thing, on adding flex it dosen't work because drag-area doesn't have properties of v-layout

**Comment by gustoase** [comment]
@bajki This project is experimental, and not yet finished. You can add your library of controls, there is an example, see **lib** folder...

  Experiment yourself)

**Comment by gustoase** [comment]
@bajki Or maybe you just did not create a new page in the project? There is a plus button

**Comment by bajki** [comment]
![Screenshot_20190315_210343](https://user-images.githubusercontent.com/24210611/54459111-fb9ab580-4765-11e9-8c1f-c7bb59d8048c.png)

It should be in one row md6 md6..
